name: Release ossrh

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release ossrh jobs

    steps:
      - uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Execute style check
        run: mvn spotless:check

      - name: Release to Apache Maven Central
        run: mvn clean deploy -Prelease-ossrh
